"""empty message

Revision ID: f875df5f5d99
Revises: 
Create Date: 2026-06-01 12:38:59.063452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f875df5f5d99'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selectedUser', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    op.execute("UPDATE users SET selectedUser = FALSE")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('selectedUser')

    # ### end Alembic commands ###
